stages:
  - test

# Define job to run unittests
unittests:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest discover -s . -p 'tests.py'
